
check_system() {
  [ "$(id -u)" -eq 0 ] || die "Please run with sudo or as root."
  [ -r /etc/os-release ] || die "/etc/os-release is missing, unknown system."
  # shellcheck disable=SC1091
  . /etc/os-release
  if [ "${ID:-}" = "debian" ] && { [ "${VERSION_ID:-}" = "12" ] || [ "${VERSION_ID:-}" = "13" ]; }; then
    ok "Detected Debian ${VERSION_ID} (${VERSION_CODENAME:-?})"
  elif [ "$PP_FORCE" = "yes" ]; then
    warn "Untested system (${PRETTY_NAME:-unknown}), continuing anyway because of --force."
  else
    die "Tested on Debian 12 and 13, found: ${PRETTY_NAME:-unknown}. Use --force to install anyway."
  fi
}

port_in_use() {
  command -v ss >/dev/null 2>&1 || return 1
  ss -Hltn "sport = :${PP_PORT}" 2>/dev/null | grep -q .
}

install_nginx() {
  local pkgs=()
  command -v nginx >/dev/null 2>&1 || pkgs+=(nginx)
  [ "$PP_TLS" = "yes" ] && ! command -v openssl >/dev/null 2>&1 && pkgs+=(openssl)
  if [ ${#pkgs[@]} -eq 0 ]; then
    ok "nginx is already installed"
  else
    say "Installing ${pkgs[*]}"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq "${pkgs[@]}" >/dev/null
    ok "${pkgs[*]} installed"
  fi
}

# Self-signed certificate for this server. An existing certificate is kept so that
# browsers that already accepted it do not warn again; it is only replaced when it
# is missing, broken, expires within 30 days or --new-cert is given.
ensure_cert() {
  [ "$PP_TLS" = "yes" ] || return 0
  if [ "$PP_NEW_CERT" = "no" ] && [ -s "$PP_CERT" ] && [ -s "$PP_KEY" ] \
     && openssl x509 -in "$PP_CERT" -noout -checkend 2592000 >/dev/null 2>&1; then
    ok "Keeping the existing certificate ($(openssl x509 -in "$PP_CERT" -noout -enddate | cut -d= -f2))"
    return 0
  fi
  say "Generating a self-signed certificate"
  local host fqdn san ip
  host="$(hostname -s 2>/dev/null || hostname)"
  fqdn="$(hostname -f 2>/dev/null || true)"
  san="DNS:${host},DNS:localhost"
  [ -n "$fqdn" ] && [ "$fqdn" != "$host" ] && [ "$fqdn" != "localhost" ] && san="${san},DNS:${fqdn}"
  san="${san},IP:127.0.0.1"
  [ -f /proc/net/if_inet6 ] && san="${san},IP:::1"
  for ip in $(hostname -I 2>/dev/null || true); do
    case "$ip" in fe80:*) continue ;; esac
    san="${san},IP:${ip}"
  done
  mkdir -p "$PP_TLS_DIR"
  chmod 700 "$PP_TLS_DIR"
  # 825 days is the longest validity Apple devices accept for TLS server certificates
  openssl req -x509 -newkey rsa:3072 -sha256 -nodes -days 825 \
    -keyout "${PP_KEY}.new" -out "${PP_CERT}.new" \
    -subj "/CN=${host}/O=PacketPilot" \
    -addext "subjectAltName=${san}" \
    -addext "basicConstraints=critical,CA:FALSE" \
    -addext "keyUsage=critical,digitalSignature,keyEncipherment" \
    -addext "extendedKeyUsage=serverAuth" >/dev/null 2>&1 \
    || die "Could not generate the certificate with openssl."
  chmod 600 "${PP_KEY}.new"
  chmod 644 "${PP_CERT}.new"
  mv "${PP_KEY}.new" "$PP_KEY"
  mv "${PP_CERT}.new" "$PP_CERT"
  ok "Certificate for ${san//,/, } (valid 825 days)"
}

write_site() {
  say "Writing nginx configuration for port ${PP_PORT}"
  local listen6="    listen [::]:${PP_PORT};"
  if [ ! -f /proc/net/if_inet6 ]; then
    listen6="    # IPv6 is not available on this system"
    warn "No IPv6 available, PacketPilot only listens on IPv4."
  fi
  local ssl="" tls="" PP_TLS_NOTE=" (--http)"
  if [ "$PP_TLS" = "yes" ]; then
    PP_TLS_NOTE=""
    ssl=" ssl"
    tls="
    ssl_certificate     ${PP_CERT};
    ssl_certificate_key ${PP_KEY};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_session_cache   shared:PacketPilot:1m;
    ssl_session_timeout 1d;
    # Plain HTTP on the HTTPS port: redirect instead of showing an error
    error_page 497 =301 https://\$host:\$server_port\$request_uri;
"
  fi
  [ -n "$ssl" ] && listen6="${listen6/:${PP_PORT};/:${PP_PORT} ssl;}"
  cat > "$PP_SITE" <<NGINX
# PacketPilot ${PP_VERSION}, generated by packetpilot-install.sh${PP_TLS_NOTE}
server {
    listen ${PP_PORT}${ssl};
${listen6}
    server_name _;
${tls}
    root ${PP_WWW};
    index index.html;
    charset utf-8;

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'" always;

    location / {
        try_files \$uri \$uri/ /index.html;
    }
    location ~* \.(js|css)\$ {
        add_header Cache-Control "no-cache" always;
        add_header X-Content-Type-Options "nosniff" always;
    }
}
NGINX
  ln -sf "$PP_SITE" "$PP_LINK"
  if [ "$PP_PORT" = "80" ] && [ -L /etc/nginx/sites-enabled/default ]; then
    warn "Port 80: the nginx default site is disabled (only the link in sites-enabled, the file stays)."
    rm -f /etc/nginx/sites-enabled/default
  fi
  nginx -t >/dev/null 2>&1 || { nginx -t; die "nginx configuration is invalid, see above."; }
  systemctl enable --now nginx >/dev/null 2>&1 || true
  systemctl reload nginx
  ok "nginx reloaded"
}

open_firewall() {
  if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
    ufw allow "${PP_PORT}/tcp" >/dev/null && ok "ufw: port ${PP_PORT}/tcp opened"
  fi
}

# Keep the previous port and the choice of HTTP or HTTPS when reinstalling
keep_settings() {
  [ -f "$PP_SITE" ] || return 0
  if [ "$PP_PORT_SET" = "no" ]; then
    local old
    old="$(awk '/^[[:space:]]*listen[[:space:]]+[0-9]+[[:space:];]/ { gsub(";", "", $2); print $2; exit }' "$PP_SITE")"
    if [ -n "$old" ] && [ "$old" != "$PP_PORT" ]; then
      PP_PORT="$old"
      ok "Keeping previous port ${PP_PORT} (change with --port)"
    fi
  fi
  # Sites written by versions before 1.2.0 never had TLS: those switch to HTTPS now
  if [ "$PP_TLS_SET" = "no" ] && grep -q "^# PacketPilot.*--http" "$PP_SITE"; then
    PP_TLS="no"
    ok "Keeping plain HTTP (switch with --https)"
  fi
}

do_install() {
  check_system
  keep_settings
  if port_in_use && [ ! -f "$PP_SITE" ]; then
    warn "Port ${PP_PORT} is already in use. If you run into problems, choose another one with --port."
  fi
  install_nginx
  ensure_cert
  say "Writing web files to ${PP_WWW}"
  local tmp
  tmp="$(mktemp -d)"
  write_files "$tmp"
  mkdir -p "$PP_ROOT"
  rm -rf "${PP_WWW}.new"
  mv "$tmp" "${PP_WWW}.new"
  rm -rf "$PP_WWW"
  mv "${PP_WWW}.new" "$PP_WWW"
  echo "$PP_VERSION" > "${PP_ROOT}/VERSION"
  chown -R root:root "$PP_ROOT"
  find "$PP_WWW" -type d -exec chmod 755 {} +
  find "$PP_WWW" -type f -exec chmod 644 {} +
  ok "$(find "$PP_WWW" -type f | wc -l) files installed"
  write_site
  open_firewall
  local ips
  ips="$(hostname -I 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+\.' | head -3 || true)"
  echo
  local scheme="http"
  [ "$PP_TLS" = "yes" ] && scheme="https"
  say "PacketPilot ${PP_VERSION} is ready:"
  if [ -n "$ips" ]; then
    for ip in $ips; do echo "      ${scheme}://${ip}:${PP_PORT}/"; done
  else
    echo "      ${scheme}://<IP-of-this-server>:${PP_PORT}/"
  fi
  echo
  if [ "$PP_TLS" = "yes" ]; then
    echo "    The certificate is self-signed, so the browser warns once. Compare the fingerprint"
    echo "    before you accept it:"
    echo "      $(openssl x509 -in "$PP_CERT" -noout -fingerprint -sha256 | cut -d= -f2)"
    echo "    Certificate: ${PP_CERT}"
    echo
  fi
  echo "    Each browser stores progress and your own networks separately."
  echo "    Update: sudo bash packetpilot-install.sh --update. Remove: --uninstall"
}

do_update() {
  [ "$(id -u)" -eq 0 ] || die "Please run with sudo or as root."
  local tmp new
  tmp="$(mktemp)"
  say "Downloading the latest version from github.com/${PP_REPO}"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$PP_SCRIPT_URL" -o "$tmp" || die "Download failed: ${PP_SCRIPT_URL}"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$tmp" "$PP_SCRIPT_URL" || die "Download failed: ${PP_SCRIPT_URL}"
  else
    die "Neither curl nor wget found. Install with: apt install curl"
  fi
  bash -n "$tmp" || die "The downloaded script is broken, aborting."
  new="$(sed -n 's/^PP_VERSION="\(.*\)"$/\1/p' "$tmp" | head -1)"
  [ -n "$new" ] || die "The downloaded script does not look like PacketPilot."
  say "Installed: $(cat "${PP_ROOT}/VERSION" 2>/dev/null || echo none), available: ${new}"
  local args=()
  [ "$PP_PORT_SET" = "yes" ] && args+=(--port "$PP_PORT")
  [ "$PP_FORCE" = "yes" ] && args+=(--force)
  [ "$PP_TLS_SET" = "yes" ] && { [ "$PP_TLS" = "yes" ] && args+=(--https) || args+=(--http); }
  [ "$PP_NEW_CERT" = "yes" ] && args+=(--new-cert)
  exec bash "$tmp" "${args[@]}"
}

do_uninstall() {
  [ "$(id -u)" -eq 0 ] || die "Please run with sudo or as root."
  say "Removing PacketPilot"
  rm -f "$PP_LINK" "$PP_SITE"
  rm -rf "$PP_ROOT"
  if command -v nginx >/dev/null 2>&1 && nginx -t >/dev/null 2>&1; then systemctl reload nginx || true; fi
  ok "PacketPilot removed. nginx itself stays installed (remove with: apt purge nginx)."
}

do_extract() {
  [ -n "$PP_EXTRACT_DIR" ] || die "Specify a target folder: --extract ./web"
  mkdir -p "$PP_EXTRACT_DIR"
  write_files "$PP_EXTRACT_DIR"
  ok "Web files extracted to ${PP_EXTRACT_DIR}. Test e.g. with: python3 -m http.server -d ${PP_EXTRACT_DIR} 8080"
}

case "$PP_ACTION" in
  install)   do_install ;;
  update)    do_update ;;
  uninstall) do_uninstall ;;
  extract)   do_extract ;;
esac
